#! /usr/bin/env node

/**
 *  @file       generate-native-env-script
 *              Generates the native evaluator enviroment init script.
 *              Outputs the file to ./native-evaluator-env.js
 *
 *  @author     Ryan Rossiter, ryan@kingsds.network
 *  @date       Sept 2020
 */

const fs = require('fs'); 
const evaluatorSetUpFiles = require('./evaluator-set-up-files.json');
const OUTPUT_FILENAME = 'native-evaluator-env.js';

const fileContents = evaluatorSetUpFiles.native.map((fileName) => {
  const localModulePath = fileName.replace(/^dcp-worker/, '.');
  const path = require.resolve(localModulePath);

  if (!path) {
    throw new Error(`Failed to resolve module path: ${fileName}`);
  }

  return fs.readFileSync(path, { encoding: 'utf8' });
});

fs.writeFileSync(OUTPUT_FILENAME, ';' + fileContents.join(';'), { encoding: 'utf8' });
console.log("Wrote native evaluator env file to", OUTPUT_FILENAME);
