#! /usr/bin/env node

/**
 *  @file       generate-native-env-script
 *              Generates the native evaluator enviroment init script.
 *              Outputs the file to ./native-evaluator-env.js
 *
 *  @author     Ryan Rossiter, ryan@kingsds.network
 *  @date       Sept 2020
 */

const fs = require('fs'); 
var path = require('path');
const evaluatorSetupFiles = require('./evaluator-setup-files'); //Changed from a .json to a js to support exports.object
const OUTPUT_FILENAME = 'native-evaluator-env.js';

const fileContents = evaluatorSetupFiles.native.map((fileName) => {
  var filePath; 
  if (/(^[.])|(\/)/.test(fileName)){
    filePath= require.resolve(fileName);
  } else {
    filePath = require.resolve(path.join('..', 'dcp-worker','libexec', 'evaluator', fileName));
  }

  if (!filePath) {
    throw new Error(`Failed to resolve module path: ${fileName}`);
  }

  return fs.readFileSync(filePath, { encoding: 'utf8' });
});

fs.writeFileSync(OUTPUT_FILENAME, ';' + fileContents.join(';'), { encoding: 'utf8' });
console.log("Wrote native evaluator env file to", OUTPUT_FILENAME);
